-- MySQL Script generated by MySQL Workbench
-- Mon Nov 29 20:58:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `id` INT NOT NULL,
  `Login` VARCHAR(45) NULL,
  `Senha` VARCHAR(10) NULL,
  `Foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_postagens` (
  `id_postagens` INT NOT NULL,
  `Titulo` VARCHAR(30) NULL,
  `Texto` VARCHAR(255) NULL,
  `Data/Hora` DATETIME(10) NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_postagens`),
  INDEX `id_usuario_fk_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id_usuario_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_temas` (
  `id_temas` INT NOT NULL,
  `Tema_livre` VARCHAR(255) NULL,
  `Descricao` VARCHAR(255) NULL,
  `id_postagens` INT NULL,
  PRIMARY KEY (`id_temas`),
  INDEX `fk_id_postagens_idx` (`id_postagens` ASC) VISIBLE,
  CONSTRAINT `fk_id_postagens`
    FOREIGN KEY (`id_postagens`)
    REFERENCES `mydb`.`tb_postagens` (`id_postagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
